"""
ai/query_router.py
====================
The decision layer.  For every incoming user question the router decides
which path to take: return from cache instantly, or call Claude with the
pre-built context.  It never queries the DB.  It never builds context itself.

Edge cases handled:
    - Empty or whitespace-only question → raises ValueError
    - Question longer than 1000 characters → truncated with a logged warning
    - Cache hit → returns instantly, no Claude API call
    - Context string missing → raises RuntimeError before calling Claude
    - Claude API call fails → raises with descriptive message

Input validations:
    - question must be a non-empty string (after stripping whitespace)

Assumptions NOT made:
    - Not assuming cache always has entries
    - Not assuming context is always available
    - Not assuming Claude always responds successfully
"""

import logging
from typing import Optional

from ai.chat_engine import call_claude
from cache.context_builder import get_current_context
from cache.response_cache import get_cached_response, store_response
from cache.snapshot import get_snapshot

logger = logging.getLogger(__name__)

# Maximum allowed question length before truncation
_MAX_QUESTION_LENGTH: int = 1000


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

def _validate_question(question: str) -> str:
    """
    Validate and sanitise the user's question.

    Args:
        question: The raw user input.

    Returns:
        The validated (and possibly truncated) question string.

    Raises:
        TypeError: If question is not a string.
        ValueError: If question is empty or whitespace-only.
    """
    if not isinstance(question, str):
        raise TypeError(f"question must be a string, got {type(question).__name__}")

    cleaned = question.strip()

    if not cleaned:
        raise ValueError("Question must not be empty or whitespace-only.")

    if len(cleaned) > _MAX_QUESTION_LENGTH:
        logger.warning(
            "Question is %d characters (limit %d). Truncating.",
            len(cleaned),
            _MAX_QUESTION_LENGTH,
        )
        cleaned = cleaned[:_MAX_QUESTION_LENGTH]

    return cleaned


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def is_cache_hit(question: str) -> bool:
    """
    Check whether a valid cached answer exists for this question.

    Used for logging and monitoring — does not modify state.

    Args:
        question: The raw user question.

    Returns:
        True if a cached answer exists, False otherwise.
    """
    try:
        cached = get_cached_response(question)
        return cached is not None
    except Exception:
        return False


def route_query(question: str) -> str:
    """
    Route an incoming user question through the cache → Claude pipeline.

    Steps:
        1. Validate question is a non-empty string
        2. Check response cache — if hit, return immediately
        3. Get current context string from context_builder
        4. Call Claude via chat_engine with context + question
        5. Store the answer in response cache
        6. Return the answer

    Args:
        question: The user's question string.

    Returns:
        The answer string — either from cache or freshly generated by Claude.

    Raises:
        TypeError: If question is not a string.
        ValueError: If question is empty or whitespace-only.
        RuntimeError: If context is unavailable or Claude call fails.
    """
    # Step 1: Validate
    step = "validation"
    try:
        question = _validate_question(question)
    except (TypeError, ValueError) as exc:
        logger.warning("Query routing failed at step [%s]: %s", step, exc)
        raise

    # Step 2: Check cache
    step = "cache_lookup"
    try:
        cached = get_cached_response(question)
        if cached is not None:
            logger.info("Cache HIT — returning cached response.")
            return cached["answer"]
        logger.debug("Cache MISS — proceeding to Claude API.")
    except Exception as exc:
        # Cache failure is non-fatal — proceed to Claude
        logger.warning(
            "Cache lookup failed (non-fatal, proceeding to Claude): %s", exc
        )

    # Step 3: Get context
    step = "context_retrieval"
    try:
        context = get_current_context()
    except RuntimeError as exc:
        logger.error("Query routing failed at step [%s]: %s", step, exc)
        raise RuntimeError(
            f"Cannot answer question — {step} failed: {exc}"
        ) from exc

    if not context or not context.strip():
        logger.error("Context string is empty after retrieval.")
        raise RuntimeError(
            "Cannot answer question — context string is empty or missing."
        )

    # Step 4: Call Claude
    step = "claude_api_call"
    try:
        answer = call_claude(context, question)
    except Exception as exc:
        logger.error("Query routing failed at step [%s]: %s", step, exc)
        raise RuntimeError(
            f"Cannot answer question — {step} failed: {exc}"
        ) from exc

    if not answer or not answer.strip():
        raise RuntimeError("Claude returned an empty response.")

    # Step 5: Store in cache
    step = "cache_storage"
    try:
        snapshot = get_snapshot()
        snapshot_time = snapshot.get("generated_at", "unknown")
        store_response(question, answer, snapshot_time)
    except Exception as exc:
        # Cache storage failure is non-fatal — we still return the answer
        logger.warning(
            "Failed to cache response (non-fatal): %s", exc
        )

    # Step 6: Return
    logger.info("Query routed successfully via Claude API.")
    return answer
